packages:
  - .

patchedDependencies:
  wouter@3.7.1: patches/wouter@3.7.1.patch

overrides:
  tailwindcss>nanoid: 3.3.7
  path-to-regexp: 0.1.13
  qs: 6.14.2
  lodash: 4.18.1
  lodash-es: 4.18.1
  dompurify: 3.4.0
  mdast-util-to-hast: 13.2.1
